/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javalt.view;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import com.javalt.dao.*;
import com.javalt.model.*;
import com.javalt.service.*;

/**
 *
 * @author PC
 */
public class ThemSanPhamPhieuNhap extends javax.swing.JFrame {

    ComboBoxModel<String> comboBoxModel;
    DefaultTableModel dfTableModel;
    ListSelectionModel listSelectionModel;
    chiTietPhieuNhap billInfo;
    UserDao_CTPhieuNhap billInfoService;
    UserDao_SanPham proService;
    String maPN;
    long thanhTien;
    /**
     * Creates new form ThemSanPhamPhieuNhap
     */
    private void setComboBoxItem(List<User_SanPham> products) {
        for (User_SanPham p : products) {
            productComboBox.addItem(p.getTenSP());
        }
    }

    private void setTableData(List<chiTietPhieuNhap> billInfos) {
        for (chiTietPhieuNhap b : billInfos) {
            dfTableModel.addRow(new Object[]{b.getMaSP(), b.getSoLuong(), b.getGiaTien()});
        }
    }

    private String convertTenSPToMaSP(List<User_SanPham> pros, String tenSP) {
        String maSP = "";
        for (User_SanPham p : pros) {
            if (tenSP.equals(p.getTenSP())) {
                maSP = p.getMaSP();
            }
        }
        return maSP;
    }

    private String convertMaSPToTenSP(List<User_SanPham> pros, String maSP) {
        String tenSP = "";
        for (User_SanPham p : pros) {
            if (maSP.equals(p.getMaSP())) {
                tenSP = p.getTenSP();
            }
        }
        return tenSP;
    }

    private long getDonGiaFromTenSP(List<User_SanPham> pros, String tenSP) {
        long donGia = 0L;
        for (User_SanPham p : pros) {
            if (tenSP.equals(p.getTenSP())) {
                donGia = (long) p.getDonGiaBan();
            }
        }
        return donGia;
    }
     private void removeAllValue() {
        quantitySpinner.setValue(1);
        priceTextField.setText("");
    }
    public ThemSanPhamPhieuNhap(String maPN) {
        initComponents();
        this.maPN = maPN;
        proService = new UserDao_SanPham();
        setComboBoxItem(proService.getListsanpham());
        billInfoService = new UserDao_CTPhieuNhap();
        dfTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        productTable.setModel(dfTableModel);
        dfTableModel.addColumn("Mã sản phẩm");
        dfTableModel.addColumn("Số lượng");
        dfTableModel.addColumn("Giá tiền");
        if (billInfoService.getUserByMaPN(maPN) != null) {
            setTableData(billInfoService.getUserByMaPN(maPN));
        }
        listSelectionModel = productTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = productTable.getSelectedRow();
                String maSP = String.valueOf(productTable.getValueAt(row, 0));
                productComboBox.setSelectedItem(convertMaSPToTenSP(proService.getListsanpham(), maSP));
                int soLg = (int) productTable.getValueAt(row, 1);
                quantitySpinner.setValue(soLg);
                priceTextField.setText(String.valueOf(productTable.getValueAt(row, 2)));
            }
        });
        billInfo = new chiTietPhieuNhap();
        billInfo.setMaPN(maPN);
//        billInfo.setMaDH(maDH);
//        System.out.println(maPX);
//        jLabel6.setText(maPX);
        thanhTien = 0L;
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        addProductButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        billTextField = new javax.swing.JTextField();
        createBillButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("THÊM SẢN PHẨM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Sản phẩm");

        productComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Số lượng");

        quantitySpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        quantitySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantitySpinnerStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tổng tiền");

        priceTextField.setEditable(false);
        priceTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        addProductButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addProductButton.setText("Thêm sản phẩm");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteButton.setText("Xoá sản phẩm");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Thành tiền");

        billTextField.setEditable(false);
        billTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        billTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billTextFieldActionPerformed(evt);
            }
        });

        createBillButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createBillButton.setText("Tạo Phiếu Nhập");
        createBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBillButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProductButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productComboBox, 0, 538, Short.MAX_VALUE)
                                    .addComponent(quantitySpinner)
                                    .addComponent(priceTextField)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(billTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createBillButton)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductButton)
                    .addComponent(deleteButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(billTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBillButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
        long donGia = 0L;
        donGia = getDonGiaFromTenSP(proService.getListsanpham(), productComboBox.getSelectedItem().toString());
        long giaTien = 0L;
        giaTien = donGia * ((int) quantitySpinner.getValue());
        priceTextField.setText("" + giaTien);
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void quantitySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantitySpinnerStateChanged
        // TODO add your handling code here:
        long donGia = 0L;
        donGia = getDonGiaFromTenSP(proService.getListsanpham(), productComboBox.getSelectedItem().toString());
        long giaTien = 0L;
        giaTien = donGia * ((int) quantitySpinner.getValue());
        priceTextField.setText("" + giaTien);
    }//GEN-LAST:event_quantitySpinnerStateChanged

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        try {
            billInfo.setMaSP(convertTenSPToMaSP(proService.getListsanpham(), productComboBox.getSelectedItem().toString()));
            billInfo.setSoLuong(Integer.valueOf(quantitySpinner.getValue().toString()));
            billInfo.setGiaTien(Long.valueOf(priceTextField.getText()));

            thanhTien += Long.valueOf(priceTextField.getText());
            billTextField.setText("" + thanhTien);
            billInfoService.addchiTietPhieuNhap(billInfo);
            //            System.out.println(billInfo.getMaPX() + " " + billInfo.getMaSP() + " " + billInfo.getGiaTien() + " " + billInfo.getSoLuong());
            removeAllValue();
            //            dfTableModel.setRowCount(0);
            //            setTableData(billInfoService.getBillInformationById(maDH));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ThemSanPhamPhieuNhap.this, "Thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = productTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ThemSanPhamPhieuNhap.this, "Vui lòng chọn sản phẩm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            billInfo.setMaSP(convertTenSPToMaSP(proService.getListsanpham(), productComboBox.getSelectedItem().toString()));
            try {
                billInfoService.deleteSanPham(maPN, billInfo.getMaSP());
                JOptionPane.showMessageDialog(ThemSanPhamPhieuNhap.this, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(ThemSanPhamPhieuNhap.this, "Thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            thanhTien = thanhTien - Long.valueOf(priceTextField.getText());
            removeAllValue();
            billTextField.setText("" + thanhTien);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dfTableModel.setRowCount(0);
        setTableData(billInfoService.getUserByMaPN(maPN));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void billTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billTextFieldActionPerformed

    private void createBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBillButtonActionPerformed
        // TODO add your handling code here:
        new ThemPhieuNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createBillButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSanPhamPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSanPhamPhieuNhap().setVisible(true);
            }
       });*/
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JTextField billTextField;
    private javax.swing.JButton createBillButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTable productTable;
    private javax.swing.JSpinner quantitySpinner;
    // End of variables declaration//GEN-END:variables
}
